name: DotMH Standard Tyescript Actions
run-name: '${{ github.actor }} - ${{ github.workflow }} - ${{ github.run_number }}'
on:
  push:
    branches:
      - main

jobs:
  TestAndLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: '9'
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'
          cache: 'pnpm'
      - run: pnpm install
      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
      - name: Build
        run: pnpm build
      - name: Publish
        run: pnpm publish --no-git-checks
